backend:
  name: git-gateway
  branch: main
  squash_merges: true
local_backend: true
publish_mode: editorial_workflow
site_url: https://blog.keithw.me
media_library:
  name: uploadcare
  config:
    publicKey: 770f402d902e72bcac7a
    tabs: "file url"
  settings:
    defaultOperations: "/format/auto/-/quality/normal/-/stretch/off/-/resize/1280x/"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "{{slug}}" # For Editorial workflow preview links in the editor
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Tag"
        name: "tags"
        widget: "select"
        options:
          - { label: "Finance", value: "finance" }
          - { label: "Lifestyle", value: "lifestyle" }
          - { label: "Miscellaneous", value: "miscellaneous" }
          - { label: "Photography", value: "photography" }
          - { label: "Technology", value: "technology" }
      - {
          label: "Share card image",
          name: "shareCardImage",
          widget: "string",
          required: false,
          hint: "Recommended Uploadcare operations: /-/format/auto/-/quality/normal/-/stretch/off/-/resize/640x/",
        }
      - { label: "Body", name: "body", widget: "markdown" }
